sonar.projectKey=smeragdus_RR.HH
sonar.organization=smeragdus
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src/main,frontend/src,Dockerfile
sonar.tests=backend/src/test
sonar.java.binaries=backend/target/classes
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**
